sidebar: left

excerpt_link: READ MORE

widgets:
  - mailchimp
  - tagcloud
  - ads
  - recent_posts
  - archive

has_mailchimp: true

google_analytics: UA-42370265-1

menu:
  Home: /
  Apps: http://app.saysua.com
  About: /about
