sidebar: left

excerpt_link: READ MORE

widgets:
  - mailchimp
  - tagcloud
  - recent_posts
  - archive

has_mailchimp: true

menu:
  Home: /
  Apps: http://app.saysua.com
  About: /about
